environment:
  nodejs_version: "LTS"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - set DEBUG=zyre* & npm run coverage

build: off
